"""add_causal_edges_table

Revision ID: 6bf550456977
Revises: c3de448acce9
Create Date: 2026-06-09 16:00:22.590457

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bf550456977"
down_revision: str | Sequence[str] | None = "c3de448acce9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "causal_edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cause_id", sa.UUID(), nullable=False),
        sa.Column("effect_id", sa.UUID(), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "strength >= 0.0 AND strength <= 1.0", name="check_causal_strength_range"
        ),
        sa.ForeignKeyConstraint(["cause_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["effect_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("causal_edges")
    # ### end Alembic commands ###
