"""initial_migration

Revision ID: 8e4e55ce22a2
Revises:
Create Date: 2026-06-09 13:38:04.953726

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e4e55ce22a2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table(
        "belief_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_kind",
            sa.Enum("NODE", "SCHEME", name="sourcetargetkind"),
            nullable=False,
        ),
        sa.Column(
            "target_kind",
            sa.Enum("NODE", "SCHEME", name="sourcetargetkind"),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "PREMISE",
                "CONCLUSION",
                "CONFLICTING",
                "CONFLICTED",
                "PREFERRED",
                "DISPREFERRED",
                name="edgerole",
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_kind != target_kind", name="check_edge_kind_bipartite"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DESCRIPTIF",
                "EMPIRIQUE",
                "NORMATIF_POSITION",
                "NORMATIF_CONCLUSION",
                "PONT_NORMATIF",
                "DEFINITIONNEL",
                name="nodetype",
            ),
            nullable=False,
        ),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0", name="check_confidence_range"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "nodes_embedding_hnsw_idx",
        "nodes",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "scheme_nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "scheme",
            sa.Enum("INFERENCE", "CONFLIT", "PREFERENCE", name="schemetype"),
            nullable=False,
        ),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "weight >= 0.0 AND weight <= 1.0", name="check_weight_range"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scheme_nodes")
    op.drop_index(
        "nodes_embedding_hnsw_idx",
        table_name="nodes",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("nodes")
    op.drop_table("edges")
    op.drop_table("belief_snapshots")
    # ### end Alembic commands ###
